on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  analyze-and-test:
    name: Analyze & Test
    runs-on: macos-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Setup Java (needed for Gradle to run in some Flutter packages)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.0+35'

      # 3. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Run analyzer
      - name: Analyze project
        run: flutter analyze

      # 6. Run unit/widget tests
      - name: Run tests
        run: flutter test --coverage

  build:
    name: Build & Release
    runs-on: macos-latest
    needs: analyze-and-test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.0+35'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      # Build Android APKs
      - run: flutter build apk --release --split-per-abi

      # Build iOS IPA (no codesign)
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # Push artifacts to GitHub Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
